(cl:in-package ros_gui-msg)
(cl:export '(M1_VELOCITY-VAL
          M1_VELOCITY
          M2_VELOCITY-VAL
          M2_VELOCITY
          M3_VELOCITY-VAL
          M3_VELOCITY
          M1_CURRENT-VAL
          M1_CURRENT
          M2_CURRENT-VAL
          M2_CURRENT
          M3_CURRENT-VAL
          M3_CURRENT
          X_ACELLERATION-VAL
          X_ACELLERATION
          Y_ACELLERATION-VAL
          Y_ACELLERATION
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          COMPASS-VAL
          COMPASS
          M1_DUTYCYCLE-VAL
          M1_DUTYCYCLE
          M2_DUTYCYCLE-VAL
          M2_DUTYCYCLE
          M3_DUTYCYCLE-VAL
          M3_DUTYCYCLE
          M1_SETPOINT-VAL
          M1_SETPOINT
          M2_SETPOINT-VAL
          M2_SETPOINT
          M3_SETPOINT-VAL
          M3_SETPOINT
          M1_INC_CONTROL_SIGNAL-VAL
          M1_INC_CONTROL_SIGNAL
          M2_INC_CONTROL_SIGNAL-VAL
          M2_INC_CONTROL_SIGNAL
          M3_INC_CONTROL_SIGNAL-VAL
          M3_INC_CONTROL_SIGNAL
          M1_CONTROL_SIGNAL-VAL
          M1_CONTROL_SIGNAL
          M2_CONTROL_SIGNAL-VAL
          M2_CONTROL_SIGNAL
          M3_CONTROL_SIGNAL-VAL
          M3_CONTROL_SIGNAL
          V-VAL
          V
          VN-VAL
          VN
          W-VAL
          W
          DELTA_TIME-VAL
          DELTA_TIME
          X_ROBOT-VAL
          X_ROBOT
          Y_ROBOT-VAL
          Y_ROBOT
          THETA_ROBOT-VAL
          THETA_ROBOT
          VREF-VAL
          VREF
          VNREF-VAL
          VNREF
          WREF-VAL
          WREF
          X_ROBOT_ODOM-VAL
          X_ROBOT_ODOM
          Y_ROBOT_ODOM-VAL
          Y_ROBOT_ODOM
          THETA_ROBOT_ODOM-VAL
          THETA_ROBOT_ODOM
          X_V1-VAL
          X_V1
          Y_V1-VAL
          Y_V1
          THETA_V1-VAL
          THETA_V1
          ID_V1-VAL
          ID_V1
          X_V2-VAL
          X_V2
          Y_V2-VAL
          Y_V2
          THETA_V2-VAL
          THETA_V2
          ID_V2-VAL
          ID_V2
))